package mening.dasturim.technovationchalange.ui.main.user.consultation.acception

import android.app.Dialog
import android.graphics.Color
import android.graphics.drawable.ColorDrawable
import android.view.Window
import androidx.core.content.ContextCompat
import androidx.lifecycle.ViewModelProvider
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.google.android.material.button.MaterialButton
import mening.dasturim.technovationchalange.R
import mening.dasturim.technovationchalange.data.constants.Constants
import mening.dasturim.technovationchalange.databinding.FragmentAcceptionBinding
import mening.dasturim.technovationchalange.ui.base.BaseFragment
import mening.dasturim.technovationchalange.ui.main.user.home.HomeVM

class AcceptionFragment : BaseFragment<FragmentAcceptionBinding, HomeVM>() {
    private lateinit var homeAdapter: AcceptionAdapter
    override fun onBound() {
        setUp()
    }

    fun setUp() {
        homeAdapter = AcceptionAdapter(requireContext()){}
        homeAdapter.setData(Constants.getCalendarItems())
        binding.rvCalendar.apply {
            layoutManager = LinearLayoutManager(context,RecyclerView.HORIZONTAL,false)
            adapter = homeAdapter

            binding.btnSubmission.setOnClickListener{
                val dialog = Dialog(context)
                dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
                dialog.setCancelable(false)
                dialog.setContentView(R.layout.item_dialog)
                val yesBtn = dialog.findViewById(R.id.btn) as MaterialButton
                yesBtn.setOnClickListener {
                    dialog.dismiss()
                }
                dialog.window?.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
                dialog.create()
                dialog.show()

            }
        }
        binding.cv.setOnClickListener {
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv2.setOnClickListener {
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv3.setOnClickListener {
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv4.setOnClickListener {
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
           binding.cv5.setOnClickListener {
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }

           binding.cv6.setOnClickListener {
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }

    binding.cv7.setOnClickListener {
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }

    binding.cv8.setOnClickListener {
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }

  binding.cv9.setOnClickListener {
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }

        binding.cv10.setOnClickListener {
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv11.setOnClickListener {
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv12.setOnClickListener {
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv13.setOnClickListener {
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv14.setOnClickListener {
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv15.setOnClickListener {
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv16.setOnClickListener {
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
  binding.cv17.setOnClickListener {
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv18.setOnClickListener {
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
binding.cv19.setOnClickListener {
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }
        binding.cv20.setOnClickListener {
            binding.cv20.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.blue))
            binding.cv.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv2.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv3.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv4.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv5.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv7.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv6.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv8.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv10.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv11.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv12.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv13.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv14.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv15.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv16.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv17.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv18.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv19.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
            binding.cv9.setCardBackgroundColor(ContextCompat.getColorStateList(requireContext(),R.color.white))
        }

    }


override fun getLayoutResId() = R.layout.fragment_acception
override val vm: HomeVM
    get() = ViewModelProvider(this).get(HomeVM::class.java)

}